// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Booking_taskApi.Models
{
    public partial class Events
    {
        [Key]
        public int Id { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [Required]
        [StringLength(10)]
        public string Title { get; set; }
        [Column(TypeName = "text")]
        public string Description { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
    }
}