// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Booking_taskApi.Models
{
    public partial class Todos
    {
        [Key]
        public int Id { get; set; }
        public int? Userid { get; set; }
        [Required]
        [StringLength(30)]
        public string Title { get; set; }
        public bool Completed { get; set; }
        [Column(TypeName = "date")]
        public DateTime CreatedAt { get; set; }
    }
}